"""Files pururu generates next to configuration.yaml, which the configuration includes."""

import logging
from pathlib import Path
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.util.file import write_utf8_file_atomic
from homeassistant.util.yaml import dump, parse_yaml

_LOGGER = logging.getLogger(__name__)

HEADER = (
    "# Generated by pururu from its configuration. "
    "Don't edit: it is rewritten on every reload.\n"
)


def _write(path: Path, content: str) -> bool:
    """Write `content` unless the file already holds it; whether it wrote.

    Bytes are compared: a file saved in another encoding is rewritten, not an error.
    """
    if path.is_file() and path.read_bytes() == content.encode("utf-8"):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    write_utf8_file_atomic(str(path), content)
    return True


async def async_write(
    hass: HomeAssistant,
    file: str,
    what: str,
    items: list[dict[str, Any]] | dict[str, dict[str, Any]],
) -> bool:
    """Write `items` to `file` if it changed; whether it did, or None on failure.

    `items` is a list, or a mapping (as an include merging named items reads
    it). `file` is relative to the configuration folder; `what` names the items
    in the log. A failure is logged, never raised: the caller must tell
    "unchanged" (False) from "failed" (None).
    """
    try:
        return await hass.async_add_executor_job(
            _write, Path(hass.config.path(file)), HEADER + dump(items)
        )
    except (OSError, HomeAssistantError) as err:
        _LOGGER.error("%s are not written to %s: %s", what, file, err)
        return False


def _read(path: Path) -> Any:
    return parse_yaml(path.read_text(encoding="utf-8")) if path.is_file() else None


async def async_read(hass: HomeAssistant, file: str) -> Any:
    """What `file` holds, parsed; None when it is missing or unreadable.

    `file` is relative to the configuration folder: after a failed write, what
    HA will load is what it still holds.
    """
    try:
        return await hass.async_add_executor_job(_read, Path(hass.config.path(file)))
    except OSError, UnicodeDecodeError, HomeAssistantError:
        return None
