"""What pururu writes for Home Assistant to run: automations and scripts, a file per kind.

Each kind is a file in a folder that configuration.yaml includes once, under
HA's own domain: HA loads it, runs it and shows it (traces, on/off, its list).
pururu gives each item the pururu entity ID, drops what the configuration no
longer has once HA no longer runs it, and raises a Repairs issue while HA
doesn't load what the file holds.
"""

from collections.abc import Collection, Iterable, Mapping
from dataclasses import dataclass
from datetime import timedelta
import logging
from pathlib import Path
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import ATTR_RESTORED, EVENT_STATE_CHANGED, SERVICE_RELOAD
from homeassistant.core import (
    Event,
    EventStateChangedData,
    HomeAssistant,
    callback,
    split_entity_id,
)
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import (
    area_registry as ar,
    entity_registry as er,
    issue_registry as ir,
)
from homeassistant.helpers.start import async_at_started
from homeassistant.util.file import write_utf8_file_atomic
from homeassistant.util.yaml import dump

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

HEADER = (
    "# Generated by pururu from its configuration. "
    "Don't edit: it is rewritten on every reload.\n"
)


@dataclass(frozen=True, kw_only=True)
class Kind:
    """An HA domain pururu generates items of: where they go, how HA includes them."""

    # HA's domain, and the platform of its items' registry entries
    domain: str
    # Relative to HA's configuration folder, as configuration.yaml's include names them
    folder: str
    file: str
    # How the include merges the folder, and so how the file is dumped: "list"
    # (automations, each with its id) or "named" (scripts, object ID -> script)
    merge: str
    # The Repairs issue while an item isn't loaded, and its translation key
    issue: str
    # The key of the entry's data holding the IDs of the items it tracks
    data_key: str
    # Words of the log messages: "an automation", "automations", "reactions"
    one: str
    plural: str
    source: str

    @property
    def include(self) -> str:
        """configuration.yaml's line for the folder.

        A folder, not the file: a missing folder loads as nothing, while a plain
        include of a missing file stops HA from loading its configuration.
        """
        return f"{self.domain} pururu: !include_dir_merge_{self.merge} {self.folder}"


@dataclass(frozen=True, kw_only=True)
class Item:
    """A generated item: its ID (its entity ID's object ID too), its HA config, its area."""

    unique_id: str
    config: Mapping[str, Any]
    # The area its registry entry goes in; None leaves it where it is
    area: str | None = None


def period(value: timedelta) -> str:
    """A time period as HA reads it: [-]HH:MM:SS, and the fraction of a second if any."""
    sign = "-" if value < timedelta(0) else ""
    minutes, seconds = divmod(abs(value), timedelta(minutes=1))
    hours, minutes = divmod(minutes, 60)
    text = f"{sign}{hours:02}:{minutes:02}:{seconds.seconds:02}"
    if seconds.microseconds:
        text += f".{seconds.microseconds:06}"
    return text


def _content(kind: Kind, items: Iterable[Item]) -> str:
    """The file: the header, then the items as the include merges them."""
    if kind.merge == "list":
        return HEADER + dump([dict(item.config) for item in items])
    return HEADER + dump({item.unique_id: dict(item.config) for item in items})


def _write(path: Path, content: str) -> bool:
    """Write `content` unless the file already holds it; whether it wrote.

    Bytes are compared: a file saved in another encoding is rewritten, not an error.
    """
    if path.is_file() and path.read_bytes() == content.encode("utf-8"):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    write_utf8_file_atomic(str(path), content)
    return True


def _free(
    hass: HomeAssistant,
    registry: er.EntityRegistry,
    kind: Kind,
    unique_id: str,
    managed: Collection[str],
) -> bool:
    """Whether <domain>.<ID> is free, or already this item's; the holder logged.

    An item with this ID is this one only if the entry manages it: else it is
    someone's own, which keeps its ID and what it does.
    """
    entity_id = f"{kind.domain}.{unique_id}"
    if (
        same := registry.async_get_entity_id(kind.domain, kind.domain, unique_id)
    ) is not None:
        if unique_id in managed:
            return True
        holder = f"{same}, {kind.one} with the same ID"
    elif (registered := registry.async_get(entity_id)) is not None:
        holder = f"the {registered.platform} integration"
    elif (state := hass.states.get(entity_id)) is not None and not state.attributes.get(
        ATTR_RESTORED
    ):
        holder = "an entity without a unique ID"
    else:
        return True
    _LOGGER.error("%s is already taken by %s; not generating it", entity_id, holder)
    return False


def _register(
    hass: HomeAssistant, registry: er.EntityRegistry, kind: Kind, item: Item
) -> None:
    """Register the item's entity ID before HA loads it, so it gets the pururu one; place it.

    HA would derive an automation's from its alias. An area that isn't created
    is left out: the device's placement already logs it.
    """
    registered = registry.async_get_or_create(
        kind.domain, kind.domain, item.unique_id, suggested_object_id=item.unique_id
    )
    if (
        item.area is not None
        and registered.area_id != item.area
        and ar.async_get(hass).async_get_area(item.area) is not None
    ):
        registry.async_update_entity(registered.entity_id, area_id=item.area)


def _remove(registry: er.EntityRegistry, kind: Kind, unique_ids: Iterable[str]) -> None:
    """Remove the entity registry entries of these items, by their IDs."""
    for unique_id in unique_ids:
        entity_id = registry.async_get_entity_id(kind.domain, kind.domain, unique_id)
        if entity_id is not None:
            registry.async_remove(entity_id)


async def _async_write(
    hass: HomeAssistant, kind: Kind, items: list[Item]
) -> bool | None:
    """Write the file if it changed; whether it did, or None on failure.

    A failure is logged, never raised: the caller must tell "unchanged" (False)
    from "failed" (None), since a failed write must drop nothing stale.
    """
    content = _content(kind, items)
    try:
        return await hass.async_add_executor_job(
            _write, Path(hass.config.path(kind.file)), content
        )
    except (OSError, HomeAssistantError) as err:
        _LOGGER.error("The %s are not written to %s: %s", kind.plural, kind.file, err)
        return None


async def _async_reload(hass: HomeAssistant, kind: Kind) -> bool:
    """Reload HA's domain, if HA has it; whether it did. A failure is logged, never raised."""
    if kind.domain not in hass.config.components:
        return False
    try:
        await hass.services.async_call(kind.domain, SERVICE_RELOAD, blocking=True)
    except HomeAssistantError as err:
        _LOGGER.error("The %s are not reloaded: %s", kind.plural, err)
        return False
    return True


@callback
def _runs(
    hass: HomeAssistant, registry: er.EntityRegistry, kind: Kind, unique_id: str
) -> bool:
    """Whether HA runs the item: its entity has a state, and not a restored placeholder.

    One HA doesn't run but has registered gets a restored placeholder at start.
    """
    entity_id = registry.async_get_entity_id(kind.domain, kind.domain, unique_id)
    state = hass.states.get(entity_id) if entity_id is not None else None
    return state is not None and not state.attributes.get(ATTR_RESTORED)


@callback
def _missing(
    hass: HomeAssistant, registry: er.EntityRegistry, kind: Kind, ids: Iterable[str]
) -> list[str]:
    """The generated items HA doesn't run; a disabled one never runs, and isn't missing."""
    missing = []
    for unique_id in ids:
        entity_id = registry.async_get_entity_id(kind.domain, kind.domain, unique_id)
        registered = registry.async_get(entity_id) if entity_id is not None else None
        if not _runs(hass, registry, kind, unique_id) and (
            registered is None or registered.disabled_by is None
        ):
            missing.append(unique_id)
    return missing


@callback
def _check_included(
    hass: HomeAssistant, registry: er.EntityRegistry, kind: Kind, ids: Iterable[str]
) -> None:
    """Raise the Repairs issue while a generated item isn't loaded, else delete it.

    The warning is logged when the issue is raised: this runs at every state
    change of the domain.
    """
    if not _missing(hass, registry, kind, ids):
        ir.async_delete_issue(hass, DOMAIN, kind.issue)
        return
    if ir.async_get(hass).async_get_issue(DOMAIN, kind.issue) is None:
        _LOGGER.warning(
            'The %s of pururu\'s %s are not loaded: add "%s" to configuration.yaml',
            kind.plural,
            kind.source,
            kind.include,
        )
    ir.async_create_issue(
        hass,
        DOMAIN,
        kind.issue,
        is_fixable=False,
        severity=ir.IssueSeverity.WARNING,
        translation_key=kind.issue,
        translation_placeholders={"include": kind.include, "file": kind.file},
    )


async def _finish(
    hass: HomeAssistant,
    entry: ConfigEntry,
    kind: Kind,
    changed: bool,
    ids: list[str],
    stale: set[str],
    checked: list[str],
) -> None:
    """Once HA has started: apply the file, drop what HA no longer runs, check the include.

    HA reloads when the file changed, and also when it doesn't run the file as
    written (a reload that failed, the include added since): the reload is
    retried. A dropped item HA still runs keeps its entity ID, and stays
    tracked, until a reload drops it. The reload is blocking: the include is
    checked on what it loaded.
    """
    registry = er.async_get(hass)
    if (
        changed
        or _missing(hass, registry, kind, checked)
        or any(_runs(hass, registry, kind, unique_id) for unique_id in stale)
    ):
        await _async_reload(hass, kind)
    running = {
        unique_id for unique_id in stale if _runs(hass, registry, kind, unique_id)
    }
    _remove(registry, kind, stale - running)
    hass.config_entries.async_update_entry(
        entry, data={**entry.data, kind.data_key: [*ids, *sorted(running)]}
    )
    _check_included(hass, registry, kind, checked)


async def async_sync(
    hass: HomeAssistant, entry: ConfigEntry, kind: Kind, items: list[Item]
) -> None:
    """Generate the items, and keep in the entry the IDs it tracks.

    Each entity ID is registered first. At start, HA has already loaded the
    file; the rest waits for HA to have started, in a task the entry's unload
    waits for, so a reload never overlaps the previous one. The tracked IDs are
    the generated ones and the dropped ones still registered: their entries go
    once HA no longer runs them. After a failed write, the file is the previous
    one: only what it holds is checked for the include. Once HA has started, a
    state change of the domain (a user's own reload) checks the include again.
    """
    registry = er.async_get(hass)
    previous = entry.data.get(kind.data_key, [])
    kept = [
        item for item in items if _free(hass, registry, kind, item.unique_id, previous)
    ]
    for item in kept:
        _register(hass, registry, kind, item)
    ids = [item.unique_id for item in kept]
    written = await _async_write(hass, kind, kept)
    stale = {
        unique_id
        for unique_id in previous
        if unique_id not in ids
        and registry.async_get_entity_id(kind.domain, kind.domain, unique_id)
        is not None
    }
    checked = ids if written is not None else [i for i in ids if i in previous]
    hass.config_entries.async_update_entry(
        entry, data={**entry.data, kind.data_key: [*ids, *sorted(stale)]}
    )

    @callback
    def of_kind(data: EventStateChangedData) -> bool:
        return split_entity_id(data["entity_id"])[0] == kind.domain

    @callback
    def changed(_event: Event[EventStateChangedData]) -> None:
        _check_included(hass, registry, kind, checked)

    @callback
    def finish(_hass: HomeAssistant) -> None:
        entry.async_create_task(
            hass,
            _finish(hass, entry, kind, bool(written), ids, stale, checked),
            f"pururu {kind.plural}",
            eager_start=False,
        )
        entry.async_on_unload(
            hass.bus.async_listen(EVENT_STATE_CHANGED, changed, event_filter=of_kind)
        )

    entry.async_on_unload(async_at_started(hass, finish))


async def async_remove(hass: HomeAssistant, entry: ConfigEntry, kind: Kind) -> None:
    """Generate nothing: an empty file, still valid for the include.

    An item HA still runs (the file couldn't be written, or the reload failed)
    keeps its entity ID.
    """
    if await _async_write(hass, kind, []) and hass.is_running:
        await _async_reload(hass, kind)
    registry = er.async_get(hass)
    _remove(
        registry,
        kind,
        [
            unique_id
            for unique_id in entry.data.get(kind.data_key, [])
            if not _runs(hass, registry, kind, unique_id)
        ],
    )
    ir.async_delete_issue(hass, DOMAIN, kind.issue)
