"""Reactions: what a device listens to, as Home Assistant automations pururu generates.

A reaction is one source (an entity of a device, a real entity, a time of day,
the sun) and, for an entity, a condition. Each becomes an automation in
pururu/automations/reactions.yaml, whose folder configuration.yaml includes.
It has no actions yet: it fires, and its trace shows when and why.
"""

from collections.abc import Collection, Iterable, Mapping
from datetime import timedelta
import logging
from pathlib import Path
from typing import Any

import voluptuous as vol

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    ATTR_ID,
    ATTR_RESTORED,
    CONF_NAME,
    SERVICE_RELOAD,
    STATE_UNAVAILABLE,
    STATE_UNKNOWN,
)
from homeassistant.core import Event, HomeAssistant, callback
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import (
    config_validation as cv,
    entity_registry as er,
    issue_registry as ir,
)
from homeassistant.helpers.start import async_at_started
from homeassistant.util.file import write_utf8_file_atomic
from homeassistant.util.yaml import dump

from .const import CONF_AUTOMATIONS, DOMAIN, ENTITY_PREFIX
from .feature import TEXT, finite_float, qualified, state_text

_LOGGER = logging.getLogger(__name__)

# The namespace of every reaction's automation ID
NAMESPACE = "reaction"
SOURCES = ("when", "entity", "at", "sun")
# Keys that only a reaction on an entity's state takes
STATE_KEYS = ("to", "from", "above", "below", "for")
AUTOMATION = "automation"
# Relative to HA's configuration folder, as configuration.yaml's include names it
FOLDER = "pururu/automations"
FILE = f"{FOLDER}/reactions.yaml"
HEADER = (
    "# Generated by pururu from its configuration. "
    "Don't edit: it is rewritten on every reload.\n"
)
# A folder, not the file: a missing folder loads as no automations, while a
# plain include of a missing file stops HA from loading its configuration
INCLUDE = f"automation pururu: !include_dir_merge_list {FOLDER}"
ISSUE = "automations_not_included"
# Fired by HA's automation.reload, the user's own included
EVENT_AUTOMATION_RELOADED = "automation_reloaded"


def _consistent(reaction: dict[str, Any]) -> dict[str, Any]:
    """One source, and the keys that go with it."""
    sources = [key for key in SOURCES if key in reaction]
    if len(sources) != 1:
        raise vol.Invalid("a reaction needs one source: when, entity, at or sun")
    if "device" in reaction and "when" not in reaction:
        raise vol.Invalid("a reaction's device goes with when")
    if "offset" in reaction and "sun" not in reaction:
        raise vol.Invalid("a reaction's offset goes with sun")
    if sources[0] in ("at", "sun"):
        if any(key in reaction for key in STATE_KEYS):
            raise vol.Invalid(
                "a reaction on at or sun takes no to, from, above, below or for"
            )
        return reaction
    if ("to" in reaction) == ("above" in reaction or "below" in reaction):
        raise vol.Invalid(
            "a reaction on a state needs to, or above and/or below, not both"
        )
    if "from" in reaction and "to" not in reaction:
        raise vol.Invalid("a reaction's from goes with to")
    if (
        "above" in reaction
        and "below" in reaction
        and reaction["above"] >= reaction["below"]
    ):
        raise vol.Invalid("a reaction's above must be lower than its below")
    return reaction


REACTION = vol.All(
    vol.Schema(
        {
            # A blank name would show the automation as its device's name alone
            vol.Required(CONF_NAME): TEXT,
            vol.Optional("when"): cv.slug,
            vol.Optional("device"): cv.slug,
            vol.Optional("entity"): cv.entity_id,
            vol.Optional("to"): state_text,
            vol.Optional("from"): state_text,
            vol.Optional("above"): finite_float,
            vol.Optional("below"): finite_float,
            vol.Optional("for"): cv.positive_time_period,
            vol.Optional("at"): cv.time,
            vol.Optional("sun"): vol.In(("sunrise", "sunset")),
            vol.Optional("offset"): cv.time_period,
        }
    ),
    _consistent,
)
# A schema of its own: ALLOW_EXTRA would let a key that isn't a slug through
SCHEMA = vol.All(vol.Schema({cv.slug: REACTION}), vol.Length(min=1))


def automation_id(device_key: str, reaction_key: str) -> str:
    """The automation's ID, and the object ID of its entity ID: the pururu pattern."""
    return f"{ENTITY_PREFIX}_{device_key}_{qualified(NAMESPACE, reaction_key)}"


def _period(value: timedelta) -> str:
    """A time period as HA reads it: [-]HH:MM:SS, and the fraction of a second if any."""
    sign = "-" if value < timedelta(0) else ""
    minutes, seconds = divmod(abs(value), timedelta(minutes=1))
    hours, minutes = divmod(minutes, 60)
    period = f"{sign}{hours:02}:{minutes:02}:{seconds.seconds:02}"
    if seconds.microseconds:
        period += f".{seconds.microseconds:06}"
    return period


def triggers(
    reaction: Mapping[str, Any], entity_id: str | None
) -> list[dict[str, Any]]:
    """The HA triggers of a validated reaction; `entity_id` is the entity it watches.

    With `to` and no `from`, a state coming back from no reading doesn't fire:
    a plug reconnecting (unavailable → off) is no "turned off".
    """
    if "at" in reaction:
        return [{"trigger": "time", "at": reaction["at"].isoformat()}]
    if "sun" in reaction:
        sun: dict[str, Any] = {"trigger": "sun", "event": reaction["sun"]}
        if "offset" in reaction:
            sun["offset"] = _period(reaction["offset"])
        return [sun]
    trigger: dict[str, Any]
    if "to" in reaction:
        trigger = {"trigger": "state", "entity_id": entity_id}
        if "from" in reaction:
            trigger["from"] = reaction["from"]
        else:
            trigger["not_from"] = [STATE_UNAVAILABLE, STATE_UNKNOWN]
        trigger["to"] = reaction["to"]
    else:
        trigger = {"trigger": "numeric_state", "entity_id": entity_id}
        for key in ("above", "below"):
            if key in reaction:
                trigger[key] = reaction[key]
    if "for" in reaction:
        trigger["for"] = _period(reaction["for"])
    return [trigger]


def automation(
    device_key: str,
    device_name: str,
    reaction_key: str,
    reaction: Mapping[str, Any],
    entity_id: str | None,
) -> dict[str, Any]:
    """The automation of a reaction: no actions yet."""
    return {
        "id": automation_id(device_key, reaction_key),
        "alias": f"{device_name} {reaction[CONF_NAME]}",
        "description": f"pururu: {device_key}, {reaction_key}",
        "triggers": triggers(reaction, entity_id),
        "actions": [],
    }


def _write(path: Path, content: str) -> bool:
    """Write `content` unless the file already holds it; whether it wrote.

    Bytes are compared: a file saved in another encoding is rewritten, not an error.
    """
    if path.is_file() and path.read_bytes() == content.encode("utf-8"):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    write_utf8_file_atomic(str(path), content)
    return True


def _free(
    hass: HomeAssistant,
    registry: er.EntityRegistry,
    unique_id: str,
    managed: Collection[str],
) -> bool:
    """Whether automation.<ID> is free, or already this automation's; the holder logged.

    An automation with this ID is this one only if the entry manages it: else it
    is someone's own, which keeps its ID and its actions.
    """
    entity_id = f"{AUTOMATION}.{unique_id}"
    if (
        same := registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id)
    ) is not None:
        if unique_id in managed:
            return True
        holder = f"{same}, an automation with the same ID"
    elif (registered := registry.async_get(entity_id)) is not None:
        holder = f"the {registered.platform} integration"
    elif (state := hass.states.get(entity_id)) is not None and not state.attributes.get(
        ATTR_RESTORED
    ):
        holder = "an entity without a unique ID"
    else:
        return True
    _LOGGER.error("%s is already taken by %s; not generating it", entity_id, holder)
    return False


def _remove(registry: er.EntityRegistry, unique_ids: Iterable[str]) -> None:
    """Remove the entity registry entries of these automations, by their IDs."""
    for unique_id in unique_ids:
        entity_id = registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id)
        if entity_id is not None:
            registry.async_remove(entity_id)


async def _async_write(
    hass: HomeAssistant, automations: list[dict[str, Any]]
) -> bool | None:
    """Write the file if it changed; whether it did, or None on failure.

    A failure is logged, never raised: the caller must tell "unchanged" (False)
    from "failed" (None), since a failed write must drop nothing stale.
    """
    try:
        return await hass.async_add_executor_job(
            _write, Path(hass.config.path(FILE)), HEADER + dump(automations)
        )
    except (OSError, HomeAssistantError) as err:
        _LOGGER.error("The automations are not written to %s: %s", FILE, err)
        return None


async def _async_reload(hass: HomeAssistant) -> bool:
    """Reload HA's automations, if HA has them; whether it did. A failure is logged, never raised."""
    if AUTOMATION not in hass.config.components:
        return False
    try:
        await hass.services.async_call(AUTOMATION, SERVICE_RELOAD, blocking=True)
    except HomeAssistantError as err:
        _LOGGER.error("The automations are not reloaded: %s", err)
        return False
    return True


@callback
def _running(hass: HomeAssistant) -> set[str]:
    """The IDs of the automations HA runs.

    One it doesn't run but has registered leaves a restored placeholder, whose
    attributes carry its registered ID too: it doesn't count.
    """
    return {
        str(state.attributes[ATTR_ID])
        for state in hass.states.async_all(AUTOMATION)
        if ATTR_ID in state.attributes and not state.attributes.get(ATTR_RESTORED)
    }


@callback
def _missing(
    hass: HomeAssistant, registry: er.EntityRegistry, ids: Iterable[str]
) -> list[str]:
    """The generated automations HA doesn't run; a disabled one never runs, and isn't missing."""
    running = _running(hass)
    missing = []
    for unique_id in ids:
        entity_id = registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id)
        registered = registry.async_get(entity_id) if entity_id is not None else None
        if unique_id not in running and (
            registered is None or registered.disabled_by is None
        ):
            missing.append(unique_id)
    return missing


@callback
def _check_included(
    hass: HomeAssistant, registry: er.EntityRegistry, ids: Iterable[str]
) -> None:
    """Raise the Repairs issue while a generated automation isn't loaded, else delete it."""
    if not _missing(hass, registry, ids):
        ir.async_delete_issue(hass, DOMAIN, ISSUE)
        return
    _LOGGER.warning(
        'The automations of pururu\'s reactions are not loaded: add "%s" '
        "to configuration.yaml",
        INCLUDE,
    )
    ir.async_create_issue(
        hass,
        DOMAIN,
        ISSUE,
        is_fixable=False,
        severity=ir.IssueSeverity.WARNING,
        translation_key=ISSUE,
        translation_placeholders={"include": INCLUDE, "file": FILE},
    )


async def _finish(
    hass: HomeAssistant,
    entry: ConfigEntry,
    changed: bool,
    ids: list[str],
    stale: set[str],
    checked: list[str],
) -> None:
    """Once HA has started: apply the file, drop what HA no longer runs, check the include.

    HA reloads when the file changed, and also when it doesn't run the file as
    written (a reload that failed, the include added since): the reload is
    retried. A dropped automation HA still runs keeps its entity ID, and stays
    tracked, until a reload drops it.
    """
    registry = er.async_get(hass)
    reloaded = False
    if changed or _missing(hass, registry, checked) or stale & _running(hass):
        reloaded = await _async_reload(hass)
    running = stale & _running(hass)
    _remove(registry, stale - running)
    hass.config_entries.async_update_entry(
        entry, data={**entry.data, CONF_AUTOMATIONS: [*ids, *sorted(running)]}
    )
    if not reloaded:  # a reload is checked when its event comes
        _check_included(hass, registry, checked)


async def async_sync(
    hass: HomeAssistant, entry: ConfigEntry, automations: list[dict[str, Any]]
) -> list[str]:
    """Generate the automations: the IDs the entry tracks.

    Each entity ID is registered first, so HA gives the automation the pururu
    one rather than one from its alias. At start, HA has already loaded the
    file; the rest waits for HA to have started, in a task the entry's unload
    waits for, so a reload never overlaps the previous one. The tracked IDs are
    the generated ones and the dropped ones still registered: their entries go
    once HA no longer runs them. After a failed write, the file is the previous
    one: only what it holds is checked for the include.
    """
    registry = er.async_get(hass)
    previous = entry.data.get(CONF_AUTOMATIONS, [])
    kept = [each for each in automations if _free(hass, registry, each["id"], previous)]
    for each in kept:
        registry.async_get_or_create(
            AUTOMATION, AUTOMATION, each["id"], suggested_object_id=each["id"]
        )
    ids = [each["id"] for each in kept]
    written = await _async_write(hass, kept)
    stale = {
        unique_id
        for unique_id in previous
        if unique_id not in ids
        and registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id) is not None
    }
    checked = ids if written is not None else [i for i in ids if i in previous]

    @callback
    def finish(_hass: HomeAssistant) -> None:
        entry.async_create_task(
            hass,
            _finish(hass, entry, bool(written), ids, stale, checked),
            "pururu reactions",
            eager_start=False,
        )

    entry.async_on_unload(async_at_started(hass, finish))

    @callback
    def reloaded(_event: Event) -> None:
        _check_included(hass, registry, checked)

    entry.async_on_unload(hass.bus.async_listen(EVENT_AUTOMATION_RELOADED, reloaded))
    return [*ids, *sorted(stale)]


async def async_remove(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Generate nothing: an empty file, still valid for the include.

    An automation HA still runs (the file couldn't be written, or the reload
    failed) keeps its entity ID.
    """
    if await _async_write(hass, []) and hass.is_running:
        await _async_reload(hass)
    tracked = set(entry.data.get(CONF_AUTOMATIONS, []))
    _remove(er.async_get(hass), tracked - _running(hass))
    ir.async_delete_issue(hass, DOMAIN, ISSUE)
