"""Reactions: what a device listens to, as Home Assistant automations pururu generates.

A reaction is one source (an entity of a device, a real entity, a time of day,
the sun) and, for an entity, a condition. Each becomes an automation in
pururu/automations.yaml, which configuration.yaml includes. It has no actions
yet: it fires, and its trace shows when and why.
"""

from collections.abc import Iterable, Mapping
from datetime import timedelta
import logging
from pathlib import Path
from typing import Any

import voluptuous as vol

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    ATTR_ID,
    ATTR_RESTORED,
    CONF_NAME,
    SERVICE_RELOAD,
    STATE_UNAVAILABLE,
    STATE_UNKNOWN,
)
from homeassistant.core import Event, HomeAssistant, callback
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import (
    config_validation as cv,
    entity_registry as er,
    issue_registry as ir,
)
from homeassistant.helpers.start import async_at_started
from homeassistant.util.file import write_utf8_file_atomic
from homeassistant.util.yaml import dump

from .const import CONF_AUTOMATIONS, DOMAIN, ENTITY_PREFIX
from .feature import finite_float, qualified, state_text

_LOGGER = logging.getLogger(__name__)

# The namespace of every reaction's automation ID
NAMESPACE = "reaction"
SOURCES = ("when", "entity", "at", "sun")
# Keys that only a reaction on an entity's state takes
STATE_KEYS = ("to", "from", "above", "below", "for")
AUTOMATION = "automation"
# Relative to HA's configuration folder, as configuration.yaml's include names it
FILE = "pururu/automations.yaml"
HEADER = (
    "# Generated by pururu from its configuration. "
    "Don't edit: it is rewritten on every reload.\n"
)
INCLUDE = f"automation pururu: !include {FILE}"
ISSUE = "automations_not_included"
# Fired by HA's automation.reload, the user's own included
EVENT_AUTOMATION_RELOADED = "automation_reloaded"


def _consistent(reaction: dict[str, Any]) -> dict[str, Any]:
    """One source, and the keys that go with it."""
    sources = [key for key in SOURCES if key in reaction]
    if len(sources) != 1:
        raise vol.Invalid("a reaction needs one source: when, entity, at or sun")
    if "device" in reaction and "when" not in reaction:
        raise vol.Invalid("a reaction's device goes with when")
    if "offset" in reaction and "sun" not in reaction:
        raise vol.Invalid("a reaction's offset goes with sun")
    if sources[0] in ("at", "sun"):
        if any(key in reaction for key in STATE_KEYS):
            raise vol.Invalid(
                "a reaction on at or sun takes no to, from, above, below or for"
            )
        return reaction
    if ("to" in reaction) == ("above" in reaction or "below" in reaction):
        raise vol.Invalid(
            "a reaction on a state needs to, or above and/or below, not both"
        )
    if "from" in reaction and "to" not in reaction:
        raise vol.Invalid("a reaction's from goes with to")
    if (
        "above" in reaction
        and "below" in reaction
        and reaction["above"] >= reaction["below"]
    ):
        raise vol.Invalid("a reaction's above must be lower than its below")
    return reaction


REACTION = vol.All(
    vol.Schema(
        {
            # A blank name would show the automation as its device's name alone
            vol.Required(CONF_NAME): vol.All(cv.string, vol.Strip, vol.Length(min=1)),
            vol.Optional("when"): cv.slug,
            vol.Optional("device"): cv.slug,
            vol.Optional("entity"): cv.entity_id,
            vol.Optional("to"): state_text,
            vol.Optional("from"): state_text,
            vol.Optional("above"): finite_float,
            vol.Optional("below"): finite_float,
            vol.Optional("for"): cv.positive_time_period,
            vol.Optional("at"): cv.time,
            vol.Optional("sun"): vol.In(("sunrise", "sunset")),
            vol.Optional("offset"): cv.time_period,
        }
    ),
    _consistent,
)
# A schema of its own: ALLOW_EXTRA would let a key that isn't a slug through
SCHEMA = vol.All(vol.Schema({cv.slug: REACTION}), vol.Length(min=1))


def automation_id(device_key: str, reaction_key: str) -> str:
    """The automation's ID, and the object ID of its entity ID: the pururu pattern."""
    return f"{ENTITY_PREFIX}_{device_key}_{qualified(NAMESPACE, reaction_key)}"


def _period(value: timedelta) -> str:
    """A time period as HA reads it: [-]HH:MM:SS, in whole seconds."""
    seconds = int(value.total_seconds())
    sign = "-" if seconds < 0 else ""
    hours, rest = divmod(abs(seconds), 3600)
    minutes, seconds = divmod(rest, 60)
    return f"{sign}{hours:02}:{minutes:02}:{seconds:02}"


def triggers(
    reaction: Mapping[str, Any], entity_id: str | None
) -> list[dict[str, Any]]:
    """The HA triggers of a validated reaction; `entity_id` is the entity it watches.

    With `to` and no `from`, a state coming back from no reading doesn't fire:
    a plug reconnecting (unavailable → off) is no "turned off".
    """
    if "at" in reaction:
        return [{"trigger": "time", "at": reaction["at"].isoformat()}]
    if "sun" in reaction:
        sun: dict[str, Any] = {"trigger": "sun", "event": reaction["sun"]}
        if "offset" in reaction:
            sun["offset"] = _period(reaction["offset"])
        return [sun]
    trigger: dict[str, Any]
    if "to" in reaction:
        trigger = {"trigger": "state", "entity_id": entity_id}
        if "from" in reaction:
            trigger["from"] = reaction["from"]
        else:
            trigger["not_from"] = [STATE_UNAVAILABLE, STATE_UNKNOWN]
        trigger["to"] = reaction["to"]
    else:
        trigger = {"trigger": "numeric_state", "entity_id": entity_id}
        for key in ("above", "below"):
            if key in reaction:
                trigger[key] = reaction[key]
    if "for" in reaction:
        trigger["for"] = _period(reaction["for"])
    return [trigger]


def automation(
    device_key: str,
    device_name: str,
    reaction_key: str,
    reaction: Mapping[str, Any],
    entity_id: str | None,
) -> dict[str, Any]:
    """The automation of a reaction: no actions yet."""
    return {
        "id": automation_id(device_key, reaction_key),
        "alias": f"{device_name} {reaction[CONF_NAME]}",
        "description": f"pururu: {device_key}, {reaction_key}",
        "triggers": triggers(reaction, entity_id),
        "actions": [],
    }


def _write(path: Path, content: str) -> bool:
    """Write `content` unless the file already holds it; whether it wrote."""
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(exist_ok=True)
    write_utf8_file_atomic(str(path), content)
    return True


def _free(hass: HomeAssistant, registry: er.EntityRegistry, unique_id: str) -> bool:
    """Whether automation.<ID> is free, or already this automation's; the holder logged."""
    if registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id) is not None:
        return True
    entity_id = f"{AUTOMATION}.{unique_id}"
    if (registered := registry.async_get(entity_id)) is not None:
        holder = f"the {registered.platform} integration"
    elif (state := hass.states.get(entity_id)) is not None and not state.attributes.get(
        ATTR_RESTORED
    ):
        holder = "an entity without a unique ID"
    else:
        return True
    _LOGGER.error("%s is already taken by %s; not generating it", entity_id, holder)
    return False


def _remove(registry: er.EntityRegistry, unique_ids: Iterable[str]) -> None:
    """Remove the entity registry entries of these automations, by their IDs."""
    for unique_id in unique_ids:
        entity_id = registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id)
        if entity_id is not None:
            registry.async_remove(entity_id)


async def _async_write(
    hass: HomeAssistant, automations: list[dict[str, Any]]
) -> bool | None:
    """Write the file if it changed; whether it did, or None on failure.

    A failure is logged, never raised: the caller must tell "unchanged" (False)
    from "failed" (None), since a failed write must drop nothing stale.
    """
    try:
        return await hass.async_add_executor_job(
            _write, Path(hass.config.path(FILE)), HEADER + dump(automations)
        )
    except (OSError, HomeAssistantError) as err:
        _LOGGER.error("The automations are not written to %s: %s", FILE, err)
        return None


async def _async_reload(hass: HomeAssistant) -> None:
    """Reload HA's automations, if HA has them; a failure is logged, never raised."""
    if AUTOMATION not in hass.config.components:
        return
    try:
        await hass.services.async_call(AUTOMATION, SERVICE_RELOAD, blocking=True)
    except HomeAssistantError as err:
        _LOGGER.error("The automations are not reloaded: %s", err)


@callback
def _check_included(
    hass: HomeAssistant, registry: er.EntityRegistry, ids: Iterable[str]
) -> None:
    """Raise the Repairs issue while a generated automation isn't loaded, else delete it.

    A disabled one is never loaded: it says nothing about the include.
    """
    loaded = {
        state.attributes.get(ATTR_ID) for state in hass.states.async_all(AUTOMATION)
    }
    missing = []
    for unique_id in ids:
        entity_id = registry.async_get_entity_id(AUTOMATION, AUTOMATION, unique_id)
        registered = registry.async_get(entity_id) if entity_id is not None else None
        if unique_id not in loaded and (
            registered is None or registered.disabled_by is None
        ):
            missing.append(unique_id)
    if not missing:
        ir.async_delete_issue(hass, DOMAIN, ISSUE)
        return
    _LOGGER.warning(
        'The automations of pururu\'s reactions are not loaded: add "%s" '
        "to configuration.yaml",
        INCLUDE,
    )
    ir.async_create_issue(
        hass,
        DOMAIN,
        ISSUE,
        is_fixable=False,
        severity=ir.IssueSeverity.WARNING,
        translation_key=ISSUE,
        translation_placeholders={"include": INCLUDE, "file": FILE},
    )


async def _finish(
    hass: HomeAssistant,
    registry: er.EntityRegistry,
    changed: bool,
    stale: set[str],
    ids: list[str],
) -> None:
    """Once HA has started: reload what changed, drop what isn't generated any more, check the include."""
    if changed:
        await _async_reload(hass)
    _remove(registry, stale)
    _check_included(hass, registry, ids)


async def async_sync(
    hass: HomeAssistant, entry: ConfigEntry, automations: list[dict[str, Any]]
) -> list[str]:
    """Generate the automations: the IDs generated.

    Each entity ID is registered first, so HA gives the automation the pururu
    one rather than one from its alias. At start, HA has already loaded the
    file; it is reloaded only when it changed, once HA has started. A failed
    write drops nothing stale: the returned IDs then also cover the previous
    ones, so a later, successful write can still clean up their registry
    entries; the include check always runs on this configuration's own IDs.
    """
    registry = er.async_get(hass)
    kept = [each for each in automations if _free(hass, registry, each["id"])]
    for each in kept:
        registry.async_get_or_create(
            AUTOMATION, AUTOMATION, each["id"], suggested_object_id=each["id"]
        )
    ids = [each["id"] for each in kept]
    written = await _async_write(hass, kept)
    previous = entry.data.get(CONF_AUTOMATIONS, [])
    if written is None:
        stale: set[str] = set()
        tracked = sorted(set(previous) | set(ids))
    else:
        stale = set(previous) - set(ids)
        tracked = ids
    changed = bool(written)

    async def finish(_hass: HomeAssistant) -> None:
        await _finish(hass, registry, changed, stale, ids)

    entry.async_on_unload(async_at_started(hass, finish))

    @callback
    def reloaded(_event: Event) -> None:
        _check_included(hass, registry, ids)

    entry.async_on_unload(hass.bus.async_listen(EVENT_AUTOMATION_RELOADED, reloaded))
    return tracked


async def async_remove(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Generate nothing: an empty file, stays valid for the include."""
    if await _async_write(hass, []) and hass.is_running:
        await _async_reload(hass)
    _remove(er.async_get(hass), entry.data.get(CONF_AUTOMATIONS, []))
    ir.async_delete_issue(hass, DOMAIN, ISSUE)
