"""generated.py over both kinds: the reactions' and notifications' automations, and the programs' scripts."""

from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from unittest.mock import patch

from homeassistant.config_entries import ConfigEntryState
from homeassistant.const import STATE_UNAVAILABLE
from homeassistant.core import CoreState, Event, HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import entity_registry as er, issue_registry as ir
from homeassistant.setup import async_setup_component
from homeassistant.util import dt as dt_util
from homeassistant.util.file import WriteError
from homeassistant.util.yaml import load_yaml_dict
import pytest
from pytest_homeassistant_custom_component.common import MockConfigEntry
import yaml

from helpers import capture, module, reload, restart, setup, tick

LOADER = "homeassistant.config.load_yaml_config_file"
HEADER = "# Generated by pururu from its configuration. Don't edit: it is rewritten on every reload.\n"


@dataclass(frozen=True)
class Case:
    """A kind, and a device generating its items."""

    domain: str
    folder: str
    file: str
    merge: str
    issue: str
    data_key: str
    one: str
    plural: str
    source: str
    # Its name in core/generated.py
    kind: str
    empty: Any
    device: str
    namespace: str
    block: str
    feature: dict[str, Any]
    item: dict[str, Any]
    process: str

    @property
    def include_key(self) -> str:
        return f"{self.domain} pururu"

    @property
    def include(self) -> str:
        return f"{self.include_key}: !include_dir_merge_{self.merge} {self.folder}"

    def unique_id(self, key: str) -> str:
        return f"pururu_{self.device}_{self.namespace}_{key}"

    def entity_id(self, key: str) -> str:
        return f"{self.domain}.{self.unique_id(key)}"

    def devices(self, *keys: str) -> dict[str, Any]:
        device: dict[str, Any] = {"name": "Coisa", **self.feature}
        if keys:
            device[self.block] = {key: dict(self.item) for key in keys}
        return {self.device: device}

    def devices_with(self, key: str, item: dict[str, Any]) -> dict[str, Any]:
        """Like `devices`, but `key` holds `item` instead of `self.item`."""
        device: dict[str, Any] = {"name": "Coisa", **self.feature, self.block: {key: item}}
        return {self.device: device}


AUTOMATION = Case(
    domain="automation", folder="pururu/automations", file="pururu/automations/automations.yaml",
    merge="list", issue="automations_not_included", data_key="automations",
    one="an automation", plural="automations", source="reactions and notifications",
    kind="AUTOMATIONS", empty=[],
    device="lights", namespace="reaction", block="reactions",
    feature={"lights": {"teto": {"entity": "light.dummy_teto", "name": "Teto"}}},
    item={"name": "Noite", "at": "22:00"},
    process="homeassistant.components.automation._async_process_config",
)
SCRIPT = Case(
    domain="script", folder="pururu/scripts", file="pururu/scripts/programs.yaml",
    merge="named", issue="scripts_not_included", data_key="scripts",
    one="a script", plural="scripts", source="programs", kind="SCRIPTS", empty={},
    device="greenhouse", namespace="program", block="programs",
    feature={"switches": {"sprinkler": {"entity": "switch.greenhouse_sprinkler", "name": "Irrigador"}}},
    item={"name": "Limpar", "sequence": [{"turn_on": "switch_sprinkler"}]},
    process="homeassistant.components.script._async_process_config",
)


@pytest.fixture(params=[AUTOMATION, SCRIPT], ids=lambda case: case.domain)
def case(request: pytest.FixtureRequest) -> Case:
    return request.param


def read(ha: HomeAssistant, case: Case) -> Any:
    """The file, as configuration.yaml's include reads it."""
    path = Path(ha.config.path(case.file))
    if not path.is_file():
        return case.empty
    return yaml.safe_load(path.read_text(encoding="utf-8")) or case.empty


def ids(ha: HomeAssistant, case: Case) -> list[str]:
    content = read(ha, case)
    return [item["id"] for item in content] if case.merge == "list" else list(content)


def including(ha: HomeAssistant, case: Case) -> Callable[..., dict[str, Any]]:
    """configuration.yaml, including pururu's file."""
    return lambda *_args, **_kwargs: {case.include_key: read(ha, case)}


def reloads(calls: list[Event], case: Case) -> list[Event]:
    return [event for event in calls
            if (event.data["domain"], event.data["service"]) == (case.domain, "reload")]


def issue(ha: HomeAssistant, case: Case) -> ir.IssueEntry | None:
    return ir.async_get(ha).async_get_issue("pururu", case.issue)


def loaded(ha: HomeAssistant, case: Case, key: str) -> bool:
    """Whether HA runs the item, not a restored placeholder."""
    state = ha.states.get(case.entity_id(key))
    return state is not None and not state.attributes.get("restored")


def warnings(caplog: pytest.LogCaptureFixture) -> int:
    """How many times the missing include was logged."""
    return len([r for r in caplog.records if "are not loaded: add" in r.getMessage()])


def entry_data(ha: HomeAssistant, case: Case) -> list[str]:
    return ha.config_entries.async_entries("pururu")[0].data[case.data_key]


@pytest.fixture
async def included(ha: HomeAssistant, case: Case) -> AsyncIterator[None]:
    """HA's domain, from a configuration.yaml that includes pururu's file."""
    with patch(LOADER, side_effect=including(ha, case)):
        assert await async_setup_component(ha, case.domain, {case.include_key: read(ha, case)})
        yield


# --- the file ----------------------------------------------------------------------------


async def test_the_file_has_the_header_and_an_item_per_key(ha: HomeAssistant, case: Case) -> None:
    assert await setup(ha, case.devices("door", "night"))
    assert Path(ha.config.path(case.file)).read_text(encoding="utf-8").startswith(HEADER)
    assert ids(ha, case) == [case.unique_id("door"), case.unique_id("night")]


async def test_without_items_the_file_is_empty(ha: HomeAssistant, case: Case) -> None:
    assert await setup(ha, case.devices())
    assert Path(ha.config.path(case.file)).is_file()
    assert read(ha, case) == case.empty


async def test_the_item_has_the_pururu_entity_id(ha: HomeAssistant, case: Case,
                                                 included: None) -> None:
    assert await setup(ha, case.devices("door"))
    assert loaded(ha, case, "door")
    registered = er.async_get(ha).async_get(case.entity_id("door"))
    assert registered is not None
    assert registered.unique_id == case.unique_id("door")


async def test_an_id_taken_by_another_integration_is_not_generated(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture) -> None:
    er.async_get(ha).async_get_or_create(case.domain, "template", "someone_else",
                                         suggested_object_id=case.unique_id("door"))
    assert await setup(ha, case.devices("door"))
    assert ids(ha, case) == []
    assert (f"{case.entity_id('door')} is already taken by the template integration; "
            "not generating it") in caplog.text
    assert er.async_get(ha).async_get(f"{case.entity_id('door')}_2") is None


async def test_sync_returns_the_ids_it_generated(ha: HomeAssistant, case: Case) -> None:
    """Not the one whose ID someone else holds: a reaction then knows its program's script is missing."""
    generated = module("core.generated")
    er.async_get(ha).async_get_or_create(
        case.domain, "template", "someone_else", suggested_object_id=case.unique_id("taken"))
    entry = MockConfigEntry(domain="pururu", source="import", data={})
    entry.add_to_hass(ha)
    items = [generated.Item(unique_id=case.unique_id(key), config={"alias": key})
             for key in ("free", "taken")]
    kind = getattr(generated, case.kind)
    assert await generated.async_sync(ha, entry, kind, items) == [case.unique_id("free")]


async def test_an_item_of_ones_own_with_the_same_id_is_not_adopted(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture) -> None:
    """An item pururu never generated keeps its ID and what it does."""
    er.async_get(ha).async_get_or_create(case.domain, case.domain, case.unique_id("door"),
                                         suggested_object_id="mine")
    assert await setup(ha, case.devices("door"))
    assert ids(ha, case) == []
    assert (f"{case.entity_id('door')} is already taken by {case.domain}.mine, {case.one} "
            "with the same ID; not generating it") in caplog.text


async def test_an_id_held_by_an_entity_without_a_unique_id_is_not_generated(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture) -> None:
    """A state with no registry entry (a template, a group): pururu never adopts it."""
    ha.states.async_set(case.entity_id("door"), "on")
    assert await setup(ha, case.devices("door"))
    assert ids(ha, case) == []
    assert (f"{case.entity_id('door')} is already taken by an entity without a unique ID; "
            "not generating it") in caplog.text


async def test_an_unchanged_file_is_neither_rewritten_nor_reloaded(
        ha: HomeAssistant, case: Case, included: None) -> None:
    assert await setup(ha, case.devices("door"))
    path = Path(ha.config.path(case.file))
    before = path.stat().st_ino
    calls = capture(ha, "call_service")
    await reload(ha, case.devices("door"))
    assert reloads(calls, case) == []
    assert path.stat().st_ino == before


async def test_a_file_in_another_encoding_is_rewritten(ha: HomeAssistant, case: Case) -> None:
    """A file the user saved as Latin-1 is no error: pururu writes its own UTF-8 over it."""
    path = Path(ha.config.path(case.file))
    path.parent.mkdir(parents=True)
    path.write_bytes("# Máquina\n".encode("latin-1"))
    assert await setup(ha, case.devices("door"))
    assert ha.config_entries.async_entries("pururu")[0].state is ConfigEntryState.LOADED
    assert ids(ha, case) == [case.unique_id("door")]


async def test_a_changed_file_reloads_its_domain(ha: HomeAssistant, case: Case,
                                                 included: None) -> None:
    assert await setup(ha, case.devices("door"))
    calls = capture(ha, "call_service")
    await reload(ha, case.devices("door", "night"))
    assert len(reloads(calls, case)) == 1
    assert loaded(ha, case, "night")


async def test_a_changed_item_raises_no_false_include_warning(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture,
        included: None) -> None:
    """A reload removes and re-adds the changed item: no issue in between."""
    assert await setup(ha, case.devices("door"))
    changed = {**case.item, "name": "Mudou"}
    await reload(ha, case.devices_with("door", changed))
    assert not [r for r in caplog.records if "are not loaded: add" in r.getMessage()]
    assert issue(ha, case) is None


async def test_a_reload_adding_items_raises_no_false_include_warning(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture, freezer: Any,
        included: None) -> None:
    """HA adds them one by one: the include isn't checked until they all are."""
    assert await setup(ha, case.devices("door"))
    caplog.clear()
    await reload(ha, case.devices("door", "night", "day"))
    await tick(ha, freezer, 5)
    assert warnings(caplog) == 0
    assert issue(ha, case) is None
    assert loaded(ha, case, "night")
    assert loaded(ha, case, "day")


async def test_a_reload_changing_items_raises_no_false_include_warning(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture, freezer: Any,
        included: None) -> None:
    assert await setup(ha, case.devices("door", "night", "day"))
    caplog.clear()
    changed = {**case.item, "name": "Mudou"}
    device = case.devices("door", "night", "day")
    device[case.device][case.block] = {"door": changed, "night": dict(changed),
                                       "day": dict(case.item)}
    await reload(ha, device)
    await tick(ha, freezer, 5)
    assert warnings(caplog) == 0
    assert issue(ha, case) is None


async def test_a_users_reload_changing_items_raises_no_false_include_warning(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture, freezer: Any,
        included: None) -> None:
    """pururu's own reload of the domain failed; the user's reloads both changed items."""
    assert await setup(ha, case.devices("door", "night"))
    changed = {**case.item, "name": "Mudou"}
    device = case.devices("door", "night")
    device[case.device][case.block] = {"door": changed, "night": dict(changed)}
    with patch(case.process, side_effect=HomeAssistantError("boom")):
        await reload(ha, device)
    caplog.clear()
    await ha.services.async_call(case.domain, "reload", blocking=True)
    await ha.async_block_till_done()
    await tick(ha, freezer, 5)
    assert warnings(caplog) == 0
    assert issue(ha, case) is None


async def test_a_dropped_item_leaves_the_file_and_the_registry(
        ha: HomeAssistant, case: Case, included: None) -> None:
    assert await setup(ha, case.devices("door", "night"))
    await reload(ha, case.devices("night"))
    assert ids(ha, case) == [case.unique_id("night")]
    assert er.async_get(ha).async_get(case.entity_id("door")) is None
    assert ha.states.get(case.entity_id("door")) is None
    assert entry_data(ha, case) == [case.unique_id("night")]


async def test_the_last_item_dropped_while_disabled_is_reloaded_away(
        ha: HomeAssistant, case: Case, included: None) -> None:
    """A disabled item doesn't run, yet HA holds its config: the emptied file must be reloaded."""
    assert await setup(ha, case.devices("door"))
    er.async_get(ha).async_update_entity(case.entity_id("door"),
                                         disabled_by=er.RegistryEntryDisabler.USER)
    await ha.async_block_till_done()
    calls = capture(ha, "call_service")
    await reload(ha, case.devices())
    assert ids(ha, case) == []
    assert len(reloads(calls, case)) == 1
    assert er.async_get(ha).async_get(case.entity_id("door")) is None


# --- the include ---------------------------------------------------------------------------


async def test_the_include_tolerates_a_missing_folder_and_reads_the_file(
        ha: HomeAssistant, case: Case) -> None:
    """Before pururu has written anything, HA still loads its configuration."""
    configuration = Path(ha.config.path("configuration.yaml"))
    configuration.write_text(f"{case.include}\n", encoding="utf-8")
    assert not Path(ha.config.path(case.folder)).exists()
    assert load_yaml_dict(configuration) == {case.include_key: case.empty}
    assert await setup(ha, case.devices("door"))
    assert load_yaml_dict(configuration) == {case.include_key: read(ha, case)}
    assert read(ha, case) != case.empty


async def test_without_the_include_an_issue_says_what_to_add(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture) -> None:
    with patch(LOADER, side_effect=lambda *_args, **_kwargs: {}):
        assert await async_setup_component(ha, case.domain, {})
        assert await setup(ha, case.devices("door"))
    found = issue(ha, case)
    assert found is not None
    assert found.severity == ir.IssueSeverity.WARNING
    assert not found.is_fixable
    assert found.translation_placeholders == {"include": case.include, "file": case.file}
    assert (f"The {case.plural} of pururu's {case.source} are not loaded: "
            f'add "{case.include}" to configuration.yaml') in caplog.text


async def test_the_warning_is_logged_once_while_the_issue_is_open(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture,
        freezer: Any) -> None:
    with patch(LOADER, side_effect=lambda *_args, **_kwargs: {}):
        assert await async_setup_component(ha, case.domain, {})
        assert await setup(ha, case.devices("door"))
    ha.states.async_set(f"{case.domain}.mine", "on")
    await tick(ha, freezer, 5)
    ha.states.async_set(f"{case.domain}.mine", "off")
    await tick(ha, freezer, 5)
    assert issue(ha, case) is not None
    assert len([r for r in caplog.records if "are not loaded: add" in r.getMessage()]) == 1


async def test_an_open_issue_is_not_raised_again(
        ha: HomeAssistant, case: Case, freezer: Any) -> None:
    """A state change of the domain while the include is still missing leaves the issue be."""
    with patch(LOADER, side_effect=lambda *_args, **_kwargs: {}):
        assert await async_setup_component(ha, case.domain, {})
        assert await setup(ha, case.devices("door"))
    assert issue(ha, case) is not None
    with patch.object(module("core.generated").ir, "async_create_issue") as create:
        ha.states.async_set(f"{case.domain}.mine", "on")
        await tick(ha, freezer, 5)
    create.assert_not_called()
    assert issue(ha, case) is not None


async def test_the_warning_is_logged_again_once_a_restored_issue_reopens(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture) -> None:
    """A restart restores a non-persistent issue as inactive: the warning must fire again."""
    ir.async_get(ha).issues[("pururu", case.issue)] = ir.IssueEntry(
        active=False,
        breaks_in_ha_version=None,
        created=dt_util.utcnow(),
        data=None,
        dismissed_version=None,
        domain="pururu",
        is_fixable=None,
        is_persistent=False,
        issue_domain=None,
        issue_id=case.issue,
        learn_more_url=None,
        severity=None,
        translation_key=None,
        translation_placeholders=None,
    )
    with patch(LOADER, side_effect=lambda *_args, **_kwargs: {}):
        assert await async_setup_component(ha, case.domain, {})
        assert await setup(ha, case.devices("door"))
    found = issue(ha, case)
    assert found is not None
    assert found.active
    warned = [r for r in caplog.records if "are not loaded: add" in r.getMessage()]
    assert len(warned) == 1


async def test_the_issue_goes_once_the_include_is_there(ha: HomeAssistant, case: Case,
                                                        freezer: Any) -> None:
    """The user adds the include and reloads the domain: no reload of pururu needed."""
    with patch(LOADER, side_effect=lambda *_args, **_kwargs: {}) as loader:
        assert await async_setup_component(ha, case.domain, {})
        assert await setup(ha, case.devices("door"))
        assert issue(ha, case) is not None
        loader.side_effect = including(ha, case)
        await ha.services.async_call(case.domain, "reload", blocking=True)
        await ha.async_block_till_done()
        await tick(ha, freezer, 5)
    assert issue(ha, case) is None
    assert loaded(ha, case, "door")


async def test_the_warning_is_logged_again_once_the_issue_is_raised_again(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture,
        freezer: Any) -> None:
    """The user drops the include and reloads the domain: warned once, then again each time."""
    with patch(LOADER, side_effect=including(ha, case)) as loader:
        assert await async_setup_component(ha, case.domain, {case.include_key: read(ha, case)})
        assert await setup(ha, case.devices("door", "night"))
        assert issue(ha, case) is None
        for times in (1, 2):
            loader.side_effect = lambda *_args, **_kwargs: {}
            await ha.services.async_call(case.domain, "reload", blocking=True)
            await ha.async_block_till_done()
            await tick(ha, freezer, 5)
            found = issue(ha, case)
            assert found is not None
            assert found.active
            assert warnings(caplog) == times
            loader.side_effect = including(ha, case)
            await ha.services.async_call(case.domain, "reload", blocking=True)
            await ha.async_block_till_done()
            await tick(ha, freezer, 5)
            assert issue(ha, case) is None
    assert warnings(caplog) == 2


async def test_with_the_include_there_is_no_issue(ha: HomeAssistant, case: Case,
                                                  included: None) -> None:
    assert await setup(ha, case.devices("door"))
    assert issue(ha, case) is None


async def test_without_items_there_is_no_issue(ha: HomeAssistant, case: Case) -> None:
    assert await setup(ha, case.devices())
    assert issue(ha, case) is None


async def test_a_disabled_item_is_no_missing_include(ha: HomeAssistant, case: Case,
                                                     included: None) -> None:
    assert await setup(ha, case.devices("door"))
    er.async_get(ha).async_update_entity(case.entity_id("door"),
                                         disabled_by=er.RegistryEntryDisabler.USER)
    await ha.async_block_till_done()
    await ha.services.async_call(case.domain, "reload", blocking=True)
    await ha.async_block_till_done()
    assert issue(ha, case) is None


# --- failures, removal, start-up -----------------------------------------------------------


def failing_write() -> Any:
    return patch.object(module("core.files"), "write_utf8_file_atomic",
                        side_effect=WriteError("disk full"))


async def test_a_failed_write_is_logged_and_the_setup_goes_on(
        ha: HomeAssistant, case: Case, caplog: pytest.LogCaptureFixture) -> None:
    with failing_write():
        assert await setup(ha, case.devices("door"))
    assert f"The {case.plural} are not written to {case.file}: disk full" in caplog.text
    assert ha.config_entries.async_entries("pururu")[0].state is ConfigEntryState.LOADED


async def test_removing_the_entry_leaves_an_empty_file(ha: HomeAssistant, case: Case,
                                                      included: None) -> None:
    assert await setup(ha, case.devices("door"))
    entry = ha.config_entries.async_entries("pururu")[0]
    await ha.config_entries.async_remove(entry.entry_id)
    await ha.async_block_till_done()
    assert Path(ha.config.path(case.file)).is_file()
    assert read(ha, case) == case.empty
    assert er.async_get(ha).async_get(case.entity_id("door")) is None
    assert ha.states.get(case.entity_id("door")) is None
    assert issue(ha, case) is None


async def test_a_failed_write_drops_nothing_stale(ha: HomeAssistant, case: Case,
                                                  included: None) -> None:
    """A dropped item whose write failed keeps its registry entry and its entry data."""
    assert await setup(ha, case.devices("door", "night"))
    with failing_write():
        await reload(ha, case.devices("night"))
    assert er.async_get(ha).async_get(case.entity_id("door")) is not None
    assert case.unique_id("door") in entry_data(ha, case)


async def test_a_failed_write_raises_no_include_issue(ha: HomeAssistant, case: Case,
                                                      included: None) -> None:
    """An item that never reached the file says nothing about the include."""
    assert await setup(ha, case.devices("door"))
    with failing_write():
        await reload(ha, case.devices("door", "night"))
    assert issue(ha, case) is None


@pytest.mark.parametrize("content", [
    pytest.param("# Máquina\n".encode("latin-1"), id="another encoding"),
    pytest.param(b"- just text\n- id: x\n", id="list items without an id"),
    pytest.param(b"just text\n", id="neither list nor mapping"),
])
async def test_after_a_failed_write_a_file_it_cannot_read_holds_nothing(
        ha: HomeAssistant, case: Case, content: bytes) -> None:
    """What HA will load is what the file holds: nothing of pururu's, so nothing is generated."""
    generated = module("core.generated")
    path = Path(ha.config.path(case.file))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    entry = MockConfigEntry(domain="pururu", source="import", data={})
    entry.add_to_hass(ha)
    items = [generated.Item(unique_id=case.unique_id("door"), config={"alias": "door"})]
    with failing_write():
        assert await generated.async_sync(ha, entry, getattr(generated, case.kind), items) == []


async def test_a_failed_removal_keeps_the_items_ids(ha: HomeAssistant, case: Case,
                                                    included: None) -> None:
    """The file still holds them: HA loads them again with their pururu IDs."""
    assert await setup(ha, case.devices("door"))
    entry = ha.config_entries.async_entries("pururu")[0]
    with failing_write():
        await ha.config_entries.async_remove(entry.entry_id)
        await ha.async_block_till_done()
    assert er.async_get(ha).async_get(case.entity_id("door")) is not None


async def test_at_first_start_the_new_file_is_reloaded_once_and_included(
        ha: HomeAssistant, case: Case) -> None:
    with patch(LOADER, side_effect=including(ha, case)):
        assert await async_setup_component(ha, case.domain, {case.include_key: read(ha, case)})
        calls = capture(ha, "call_service")
        await restart(ha, case.devices("door"))
    state = ha.states.get(case.entity_id("door"))
    assert state is not None
    assert state.state != STATE_UNAVAILABLE
    assert loaded(ha, case, "door")
    assert len(reloads(calls, case)) == 1
    assert issue(ha, case) is None


async def test_a_restart_with_an_unchanged_file_reloads_nothing(
        ha: HomeAssistant, case: Case) -> None:
    """Every restart: HA loads the file it already holds, then pururu finds it unchanged."""
    assert await setup(ha, case.devices("door"))
    entry = ha.config_entries.async_entries("pururu")[0]
    await ha.config_entries.async_unload(entry.entry_id)
    await ha.async_block_till_done()
    ha.set_state(CoreState.not_running)
    with patch(LOADER, side_effect=including(ha, case)):
        assert await async_setup_component(ha, case.domain, {case.include_key: read(ha, case)})
        calls = capture(ha, "call_service")
        assert await ha.config_entries.async_setup(entry.entry_id)
        await ha.async_start()
        await ha.async_block_till_done()
    assert reloads(calls, case) == []
    assert loaded(ha, case, "door")
    assert issue(ha, case) is None


async def test_items_not_loaded_are_reloaded_at_the_next_reload(
        ha: HomeAssistant, case: Case) -> None:
    """A reload that didn't take (no include yet, or it failed) is retried, the file unchanged."""
    with patch(LOADER, side_effect=lambda *_args, **_kwargs: {}) as loader:
        assert await async_setup_component(ha, case.domain, {})
        assert await setup(ha, case.devices("door"))
        assert not loaded(ha, case, "door")
        loader.side_effect = including(ha, case)
        calls = capture(ha, "call_service")
        await reload(ha, case.devices("door"))
    assert len(reloads(calls, case)) == 1
    assert loaded(ha, case, "door")
    assert issue(ha, case) is None


async def test_a_failed_reload_keeps_what_is_still_loaded_and_is_retried(
        ha: HomeAssistant, case: Case, included: None,
        caplog: pytest.LogCaptureFixture) -> None:
    """A dropped item HA still runs keeps its pururu ID until a reload drops it."""
    assert await setup(ha, case.devices("door", "night"))
    with patch(case.process, side_effect=HomeAssistantError("boom")):
        await reload(ha, case.devices("night"))
    assert f"The {case.plural} are not reloaded: boom" in caplog.text
    assert loaded(ha, case, "door")
    assert er.async_get(ha).async_get(case.entity_id("door")) is not None
    assert case.unique_id("door") in entry_data(ha, case)
    await reload(ha, case.devices("night"))
    assert not loaded(ha, case, "door")
    assert er.async_get(ha).async_get(case.entity_id("door")) is None
    assert entry_data(ha, case) == [case.unique_id("night")]
