"""Alert2's alerts: pururu writes one per alert with notify, for a made-up washer."""

from pathlib import Path
import re
from typing import Any
from unittest.mock import patch

from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import entity_registry as er, issue_registry as ir
from homeassistant.helpers.template import Template
from homeassistant.util.file import WriteError
from homeassistant.util.yaml import load_yaml_dict
import pytest
import yaml

from helpers import module, reload, setup

KEY = "dummy_washer"
POWER = "sensor.dummy_plug_power"
APPLIANCE: dict[str, Any] = {
    "power": POWER,
    "running_program": {"above": 4, "on_delay": {"minutes": 1}, "off_delay": {"minutes": 2}},
}
NOTIFY = {"message": "Overload!", "done_message": "Back to normal."}
OVERLOAD = {"name": "Overload", "when": "appliance_power", "above": 2500}
FILE = "pururu/alert2/alerts.yaml"
INCLUDE = "alerts: !include_dir_merge_list pururu/alert2"
SENSOR = "binary_sensor.pururu_dummy_washer_alert_overload"


def devices(**alerts: dict[str, Any]) -> dict[str, Any]:
    device: dict[str, Any] = {"name": "Dummy washer", "appliance": APPLIANCE}
    if alerts:
        device["alerts"] = alerts
    return {KEY: device}


def written(hass: HomeAssistant) -> list[dict[str, Any]]:
    """The Alert2 alerts pururu wrote, as the include reads them."""
    path = Path(hass.config.path(FILE))
    if not path.is_file():
        return []
    return yaml.safe_load(path.read_text(encoding="utf-8")) or []


# --- the file ---------------------------------------------------------------------------


async def test_an_alert_with_notify_is_an_alert2_alert(ha: HomeAssistant) -> None:
    assert await setup(ha, devices(overload={**OVERLOAD, "priority": "high", "notify": NOTIFY}))
    text = Path(ha.config.path(FILE)).read_text(encoding="utf-8")
    assert text.startswith("# Generated by pururu from its configuration. Don't edit: ")
    assert written(ha) == [{
        "domain": "pururu",
        "name": "dummy_washer_alert_overload",
        "friendly_name": "Dummy washer Overload",
        "condition_on": f"{{{{ is_state('{SENSOR}', 'on') }}}}",
        "condition_off": f"{{{{ is_state('{SENSOR}', 'off') }}}}",
        "priority": "high",
        "message": "Overload!",
        "done_message": "Back to normal.",
    }]


@pytest.mark.parametrize("alerts", [
    pytest.param({"overload": OVERLOAD}, id="without notify"),
    pytest.param({}, id="without alerts"),
])
async def test_the_file_is_an_empty_list_without_notify(ha: HomeAssistant,
                                                        alerts: dict[str, Any]) -> None:
    assert await setup(ha, devices(**alerts))
    assert Path(ha.config.path(FILE)).is_file()
    assert written(ha) == []


async def test_text_with_a_brace_is_not_a_template(ha: HomeAssistant) -> None:
    """Alert2 renders these fields: what the user wrote must show as written."""
    notify = {"message": "{{ 1 + 1 }} W", "done_message": "ok"}
    assert await setup(ha, devices(overload={**OVERLOAD, "name": "{x}", "notify": notify}))
    [entry] = written(ha)
    assert entry["message"] == "{% raw %}{{ 1 + 1 }} W{% endraw %}"
    assert entry["friendly_name"] == "{% raw %}Dummy washer {x}{% endraw %}"
    assert entry["done_message"] == "ok"


@pytest.mark.parametrize("text", [
    pytest.param("{{ 1 + 1 }} W", id="expression"),
    pytest.param("a {% endraw %} b", id="endraw"),
    pytest.param("{%- endraw -%}{% if x %}", id="endraw trimmed and a tag"),
    pytest.param("{# not a comment #}", id="comment"),
])
async def test_alert2_renders_the_text_as_written(ha: HomeAssistant, text: str) -> None:
    """Even text that would end a raw block renders to itself."""
    notify = {"message": text, "done_message": text}
    assert await setup(ha, devices(overload={**OVERLOAD, "name": text, "notify": notify}))
    [entry] = written(ha)
    for field, expected in (("message", text), ("done_message", text),
                            ("friendly_name", f"Dummy washer {text}")):
        assert Template(entry[field], ha).async_render(parse_result=False) == expected, field


async def test_the_conditions_follow_a_renamed_alert(ha: HomeAssistant) -> None:
    assert await setup(ha, devices(overload={**OVERLOAD, "notify": NOTIFY}))
    er.async_get(ha).async_update_entity(SENSOR, new_entity_id="binary_sensor.mine")
    await ha.async_block_till_done()
    [entry] = written(ha)
    assert entry["name"] == "dummy_washer_alert_overload"
    assert entry["condition_on"] == "{{ is_state('binary_sensor.mine', 'on') }}"


async def test_an_alert_not_created_is_not_written(ha: HomeAssistant) -> None:
    month = {"name": "Month", "when": "appliance_runtime_month", "above": 1, "notify": NOTIFY}
    assert await setup(ha, devices(month=month, overload={**OVERLOAD, "notify": NOTIFY}))
    assert [entry["name"] for entry in written(ha)] == ["dummy_washer_alert_overload"]


async def test_the_include_tolerates_a_missing_folder_and_reads_the_file(
        ha: HomeAssistant) -> None:
    """Before pururu has written anything, HA still loads its configuration."""
    configuration = Path(ha.config.path("configuration.yaml"))
    configuration.write_text(f"alert2:\n  {INCLUDE}\n", encoding="utf-8")
    assert load_yaml_dict(configuration) == {"alert2": {"alerts": []}}
    assert await setup(ha, devices(overload={**OVERLOAD, "notify": NOTIFY}))
    assert load_yaml_dict(configuration) == {"alert2": {"alerts": written(ha)}}
    assert written(ha) != []


# --- Alert2, reloads, the include --------------------------------------------------------


class FakeAlert2:
    """Alert2 as pururu sees it: its reload reads the included file into its alerts."""

    def __init__(self, hass: HomeAssistant, *, included: bool = True) -> None:
        self.hass = hass
        self.included = included
        self.fails: Exception | None = None
        self.reloads = 0
        hass.config.components.add("alert2")
        hass.services.async_register("alert2", "reload", self._reload)

    async def _reload(self, _call: ServiceCall) -> None:
        if self.fails is not None:
            raise self.fails
        self.reloads += 1
        for entity_id in self.hass.states.async_entity_ids("alert2"):
            self.hass.states.async_remove(entity_id)
        if self.included:
            for each in written(self.hass):
                self.hass.states.async_set(f"alert2.{each['domain']}_{each['name']}", "off")


@pytest.fixture
def alert2(ha: HomeAssistant) -> FakeAlert2:
    return FakeAlert2(ha)


ALERT2 = "alert2.pururu_dummy_washer_alert_overload"
WITH_NOTIFY = {"overload": {**OVERLOAD, "notify": NOTIFY}}


def issue(ha: HomeAssistant) -> ir.IssueEntry | None:
    return ir.async_get(ha).async_get_issue("pururu", "alert2_not_included")


async def test_a_new_file_reloads_alert2(ha: HomeAssistant, alert2: FakeAlert2) -> None:
    assert await setup(ha, devices(**WITH_NOTIFY))
    assert alert2.reloads == 1
    assert ha.states.get(ALERT2) is not None
    assert issue(ha) is None


async def test_an_unchanged_file_reloads_nothing(ha: HomeAssistant, alert2: FakeAlert2) -> None:
    assert await setup(ha, devices(**WITH_NOTIFY))
    await reload(ha, devices(**WITH_NOTIFY))
    assert alert2.reloads == 1


async def test_a_changed_file_reloads_alert2(ha: HomeAssistant, alert2: FakeAlert2) -> None:
    assert await setup(ha, devices(**WITH_NOTIFY))
    await reload(ha, devices(other={**OVERLOAD, "notify": NOTIFY}))
    assert alert2.reloads == 2
    assert ha.states.get(ALERT2) is None
    assert ha.states.get("alert2.pururu_dummy_washer_alert_other") is not None


async def test_a_restored_placeholder_is_not_running(ha: HomeAssistant,
                                                    alert2: FakeAlert2) -> None:
    """At start, HA shows Alert2's registered alert as restored until Alert2 declares it."""
    assert await setup(ha, devices(**WITH_NOTIFY))
    ha.states.async_set(ALERT2, "unavailable", {"restored": True})
    await reload(ha, devices(**WITH_NOTIFY))
    assert alert2.reloads == 2
    assert not ha.states.get(ALERT2).attributes.get("restored")


INCLUDE_WARNING = ("Alert2 doesn't run pururu's alerts: add \"alerts: !include_dir_merge_list "
                   "pururu/alert2\" to the alert2: block of configuration.yaml")


async def test_without_the_include_an_issue_says_what_to_add(
        ha: HomeAssistant, caplog: pytest.LogCaptureFixture) -> None:
    FakeAlert2(ha, included=False)
    assert await setup(ha, devices(**WITH_NOTIFY))
    found = issue(ha)
    assert found is not None
    assert found.severity == ir.IssueSeverity.WARNING
    assert not found.is_fixable
    assert found.translation_placeholders == {"include": INCLUDE, "file": FILE}
    assert INCLUDE_WARNING in caplog.text


async def test_the_include_warning_is_logged_once_while_its_issue_is_open(
        ha: HomeAssistant, caplog: pytest.LogCaptureFixture) -> None:
    """As the scripts' and automations' issues: an open issue isn't warned about again at each reload."""
    FakeAlert2(ha, included=False)
    assert await setup(ha, devices(**WITH_NOTIFY))
    await reload(ha, devices(**WITH_NOTIFY))
    assert issue(ha) is not None
    assert caplog.text.count(INCLUDE_WARNING) == 1


async def test_once_included_the_next_reload_retries_and_the_issue_goes(
        ha: HomeAssistant) -> None:
    alert2 = FakeAlert2(ha, included=False)
    assert await setup(ha, devices(**WITH_NOTIFY))
    alert2.included = True
    await reload(ha, devices(**WITH_NOTIFY))
    assert alert2.reloads == 2
    assert ha.states.get(ALERT2) is not None
    assert issue(ha) is None


async def test_without_alerts_with_notify_there_is_no_issue(ha: HomeAssistant) -> None:
    FakeAlert2(ha, included=False)
    assert await setup(ha, devices(overload=OVERLOAD))
    assert issue(ha) is None


async def test_without_alert2_nothing_is_reloaded_and_there_is_no_issue(
        ha: HomeAssistant) -> None:
    assert await setup(ha, devices(**WITH_NOTIFY))
    assert written(ha) != []
    assert issue(ha) is None


async def test_a_disabled_alert2_alert_is_no_missing_include(ha: HomeAssistant) -> None:
    er.async_get(ha).async_get_or_create(
        "alert2", "alert2", "d=pururu-n=dummy_washer_alert_overload",
        suggested_object_id="pururu_dummy_washer_alert_overload",
        disabled_by=er.RegistryEntryDisabler.USER)
    alert2 = FakeAlert2(ha, included=False)
    assert await setup(ha, devices(**WITH_NOTIFY))
    await reload(ha, devices(**WITH_NOTIFY))
    assert alert2.reloads == 1
    assert issue(ha) is None


async def test_a_failed_reload_is_logged_raises_no_issue_and_is_retried(
        ha: HomeAssistant, caplog: pytest.LogCaptureFixture) -> None:
    alert2 = FakeAlert2(ha)
    alert2.fails = HomeAssistantError("boom")
    assert await setup(ha, devices(**WITH_NOTIFY))
    [logged] = [r for r in caplog.records if r.getMessage() == "Alert2 is not reloaded: boom"]
    assert logged.exc_info is None, "an expected failure: the message says it all"
    assert issue(ha) is None
    alert2.fails = None
    await reload(ha, devices(**WITH_NOTIFY))
    assert alert2.reloads == 1
    assert ha.states.get(ALERT2) is not None


async def test_a_failed_write_is_logged_and_reloads_nothing(
        ha: HomeAssistant, alert2: FakeAlert2, caplog: pytest.LogCaptureFixture) -> None:
    with patch.object(module("core.files"), "write_utf8_file_atomic",
                      side_effect=WriteError("disk full")):
        assert await setup(ha, devices(**WITH_NOTIFY))
    assert f"The Alert2 alerts are not written to {FILE}: disk full" in caplog.text
    assert alert2.reloads == 0
    assert issue(ha) is None
    assert ha.states.get(SENSOR) is not None


async def test_removing_the_entry_empties_the_file_and_reloads(
        ha: HomeAssistant) -> None:
    alert2 = FakeAlert2(ha, included=False)
    assert await setup(ha, devices(**WITH_NOTIFY))
    assert issue(ha) is not None
    entry = ha.config_entries.async_entries("pururu")[0]
    await ha.config_entries.async_remove(entry.entry_id)
    await ha.async_block_till_done()
    assert written(ha) == []
    assert alert2.reloads == 2
    assert issue(ha) is None


async def test_a_changed_alert_whose_reload_failed_is_reloaded_at_the_next_reload(
        ha: HomeAssistant, alert2: FakeAlert2) -> None:
    """Alert2 still runs the alert as it was: only a reload applies the new file."""
    assert await setup(ha, devices(**WITH_NOTIFY))
    changed = devices(overload={**OVERLOAD, "notify": {**NOTIFY, "message": "Too much!"}})
    alert2.fails = HomeAssistantError("boom")
    await reload(ha, changed)
    alert2.fails = None
    await reload(ha, changed)
    assert alert2.reloads == 2


async def test_any_error_of_alert2s_reload_is_logged(
        ha: HomeAssistant, caplog: pytest.LogCaptureFixture) -> None:
    """Alert2 is a third party: whatever its reload raises must not escape."""
    alert2 = FakeAlert2(ha, included=False)
    assert await setup(ha, devices(**WITH_NOTIFY))
    assert issue(ha) is not None
    alert2.fails = NameError("repot")
    await reload(ha, devices(other={**OVERLOAD, "notify": NOTIFY}))
    [logged] = [r for r in caplog.records if r.getMessage() == "Alert2 is not reloaded"]
    assert logged.exc_info is not None, "a bug of Alert2's: the traceback helps report it"
    assert isinstance(logged.exc_info[1], NameError)
    entry = ha.config_entries.async_entries("pururu")[0]
    await ha.config_entries.async_remove(entry.entry_id)
    await ha.async_block_till_done()
    assert issue(ha) is None


async def test_a_failed_reload_at_removal_is_retried_when_pururu_comes_back(
        ha: HomeAssistant, alert2: FakeAlert2) -> None:
    """The empty file is then unchanged: only the pending reload drops the old alerts."""
    assert await setup(ha, devices(**WITH_NOTIFY))
    alert2.fails = HomeAssistantError("boom")
    entry = ha.config_entries.async_entries("pururu")[0]
    await ha.config_entries.async_remove(entry.entry_id)
    await ha.async_block_till_done()
    assert written(ha) == []
    assert ha.states.get(ALERT2) is not None
    alert2.fails = None
    await reload(ha, devices(overload=OVERLOAD))
    assert written(ha) == []
    assert alert2.reloads == 2
    assert ha.states.get(ALERT2) is None


# --- the docs ----------------------------------------------------------------------------

ALERTS_PAGE = Path(__file__).resolve().parents[1] / "docs/concepts/alerts.mdx"


def test_the_documented_include_is_the_one_pururu_asks_for(ha: HomeAssistant) -> None:
    block = re.search(r"```yaml[^\n]*\n(alert2:\n.*?)```", ALERTS_PAGE.read_text(), re.DOTALL)
    assert block is not None, "no alert2: block on the alerts page"
    assert f"  {module('outputs.alert2_alerts').INCLUDE}\n" in block[1]
    assert "generator" not in block[1]
