"""Alert2's alerts: pururu writes one per alert with notify, for a made-up washer."""

from pathlib import Path
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er
from homeassistant.util.yaml import load_yaml_dict
import pytest
import yaml

from helpers import setup

KEY = "demo_washer"
POWER = "sensor.demo_plug_power"
APPLIANCE: dict[str, Any] = {
    "power": POWER,
    "running": {"threshold": 4, "on_delay": {"minutes": 1}, "off_delay": {"minutes": 2}},
}
NOTIFY = {"message": "Overload!", "done_message": "Back to normal."}
OVERLOAD = {"name": "Overload", "when": "appliance_power", "above": 2500}
FILE = "pururu/alert2/alerts.yaml"
INCLUDE = "alerts: !include_dir_merge_list pururu/alert2"
SENSOR = "binary_sensor.pururu_demo_washer_alert_overload"


def devices(**alerts: dict[str, Any]) -> dict[str, Any]:
    device: dict[str, Any] = {"name": "Demo washer", "appliance": APPLIANCE}
    if alerts:
        device["alerts"] = alerts
    return {KEY: device}


def written(hass: HomeAssistant) -> list[dict[str, Any]]:
    """The Alert2 alerts pururu wrote, as the include reads them."""
    path = Path(hass.config.path(FILE))
    if not path.is_file():
        return []
    return yaml.safe_load(path.read_text(encoding="utf-8")) or []


# --- the file ---------------------------------------------------------------------------


async def test_an_alert_with_notify_is_an_alert2_alert(ha: HomeAssistant) -> None:
    assert await setup(ha, devices(overload={**OVERLOAD, "priority": "high", "notify": NOTIFY}))
    text = Path(ha.config.path(FILE)).read_text(encoding="utf-8")
    assert text.startswith("# Generated by pururu from its configuration. Don't edit: ")
    assert written(ha) == [{
        "domain": "pururu",
        "name": "demo_washer_alert_overload",
        "friendly_name": "Demo washer Overload",
        "condition_on": f"{{{{ is_state('{SENSOR}', 'on') }}}}",
        "condition_off": f"{{{{ is_state('{SENSOR}', 'off') }}}}",
        "priority": "high",
        "message": "Overload!",
        "done_message": "Back to normal.",
    }]


@pytest.mark.parametrize("alerts", [
    pytest.param({"overload": OVERLOAD}, id="without notify"),
    pytest.param({}, id="without alerts"),
])
async def test_the_file_is_an_empty_list_without_notify(ha: HomeAssistant,
                                                        alerts: dict[str, Any]) -> None:
    assert await setup(ha, devices(**alerts))
    assert Path(ha.config.path(FILE)).is_file()
    assert written(ha) == []


async def test_text_with_a_brace_is_not_a_template(ha: HomeAssistant) -> None:
    """Alert2 renders these fields: what the user wrote must show as written."""
    notify = {"message": "{{ 1 + 1 }} W", "done_message": "ok"}
    assert await setup(ha, devices(overload={**OVERLOAD, "name": "{x}", "notify": notify}))
    [entry] = written(ha)
    assert entry["message"] == "{% raw %}{{ 1 + 1 }} W{% endraw %}"
    assert entry["friendly_name"] == "{% raw %}Demo washer {x}{% endraw %}"
    assert entry["done_message"] == "ok"


async def test_the_conditions_follow_a_renamed_alert(ha: HomeAssistant) -> None:
    assert await setup(ha, devices(overload={**OVERLOAD, "notify": NOTIFY}))
    er.async_get(ha).async_update_entity(SENSOR, new_entity_id="binary_sensor.mine")
    await ha.async_block_till_done()
    [entry] = written(ha)
    assert entry["name"] == "demo_washer_alert_overload"
    assert entry["condition_on"] == "{{ is_state('binary_sensor.mine', 'on') }}"


async def test_an_alert_not_created_is_not_written(ha: HomeAssistant) -> None:
    month = {"name": "Month", "when": "appliance_runtime_month", "above": 1, "notify": NOTIFY}
    assert await setup(ha, devices(month=month, overload={**OVERLOAD, "notify": NOTIFY}))
    assert [entry["name"] for entry in written(ha)] == ["demo_washer_alert_overload"]


async def test_the_include_tolerates_a_missing_folder_and_reads_the_file(
        ha: HomeAssistant) -> None:
    """Before pururu has written anything, HA still loads its configuration."""
    configuration = Path(ha.config.path("configuration.yaml"))
    configuration.write_text(f"alert2:\n  {INCLUDE}\n", encoding="utf-8")
    assert load_yaml_dict(configuration) == {"alert2": {"alerts": []}}
    assert await setup(ha, devices(overload={**OVERLOAD, "notify": NOTIFY}))
    assert load_yaml_dict(configuration) == {"alert2": {"alerts": written(ha)}}
    assert written(ha) != []
